# Generated by Django 2.1.7 on 2019-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_propietarios',
            old_name='id_auto',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='auto_propietarios',
            old_name='id_propietario',
            new_name='propietario',
        ),
        migrations.RenameField(
            model_name='autos',
            old_name='marca_id',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='autos',
            old_name='tipo_id',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='propietarios',
            name='active',
        ),
        migrations.AddField(
            model_name='propietarios',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='autos',
            name='placa',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
